@REM python TaskScheduler.py --config_file TASK_2/scheduler.json
@REM for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_1_rand_c_title --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_1_rand_c_titleFontSize --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_1_rand_c_bgColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_1_rand_c_barColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_1_rand_c_strokeColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_1_rand_c_barWidth --testdataName testdata_%%I
for %%I in (1,2,3) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_1_rand_c_strokeWidth --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_1_rand_c_markPosition --testdataName testdata_%%I
for %%I in (1,2,3) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_1_rand_c_data --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_3_rand_c_title --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_3_rand_c_titleFontSize --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_3_rand_c_bgColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_3_rand_c_barColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_3_rand_c_strokeColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_3_rand_c_barWidth --testdataName testdata_%%I
for %%I in (1,2,3) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_3_rand_c_strokeWidth --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_3_rand_c_markPosition --testdataName testdata_%%I
for %%I in (1,2,3) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_3_rand_c_data --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_2_rand_c_title --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_2_rand_c_titleFontSize --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_2_rand_c_bgColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_2_rand_c_barColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_2_rand_c_strokeColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_2_rand_c_barWidth --testdataName testdata_%%I
for %%I in (1,2,3) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_2_rand_c_strokeWidth --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_2_rand_c_markPosition --testdataName testdata_%%I
for %%I in (1,2,3) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_2_rand_c_data --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_4_rand_c_title --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_4_rand_c_titleFontSize --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_4_rand_c_bgColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_4_rand_c_barColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_4_rand_c_strokeColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_4_rand_c_barWidth --testdataName testdata_%%I
for %%I in (1,2,3) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_4_rand_c_strokeWidth --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_4_rand_c_markPosition --testdataName testdata_%%I
for %%I in (1,2,3) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_4_rand_c_data --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_5_rand_c_title --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_5_rand_c_titleFontSize --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_5_rand_c_bgColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_5_rand_c_barColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_5_rand_c_strokeColorL --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_5_rand_c_barWidth --testdataName testdata_%%I
for %%I in (1,2,3) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_5_rand_c_strokeWidth --testdataName testdata_%%I
for %%I in (1,2,3,4,5,6,7) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_5_rand_c_markPosition --testdataName testdata_%%I
for %%I in (1,2,3) do python GenDataset.py --config_file TASK_2/genData_test.json --datasetName posLen_tp_5_rand_c_data --testdataName testdata_%%I